import Head from 'next/head';
import React from 'react';
import BannerCategory from '../../components/BannerCategory';
import Header from '../../components/Header';

const cat = () => {
  return (
    <div>
        <Head>
            <title>Código Hábil</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <BannerCategory />
        <CategorySection />

    </div>
  )
};

export default cat;
