import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Banner from '../components/Banner'
import MainHomepage from '../components/MainHomepage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Código Hábil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/*Header*/}
      <Header />
      {/*Banner*/}
      <Banner />
      {/*Main*/}
      <MainHomepage />


    </div>
  )
}
